### ISSUE TITLE
[Question] Will this repo get regular updates / fixes?

### ISSUE THREAD

**Issue by Amia33** [devome/wechat-bin#4]
I'm from AUR.  
As we all know, some axxhole is trying to control how wechat packages are delivered in AUR.  
Just now, package `wechat-universal-bwrap` has announced their github repo as a maintenance source.  
I wonder if this repo is similar to that.

**Comment by devome** [comment]
Yes, this repository will be updated normally.

**Comment by devome** [comment]
OK. But maybe wechat-bin@aur will still be deleted.
